openapi: "3.0.3"
info:
  title: URL Shortener API
  description: An API for shortening URLs and redirecting to original URLs
  version: 1.0.0
paths:
  /shortened-urls:
    put:
      summary: Shorten URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: The URL to be shortened
              required:
                - url
      responses:
        '200':
          description: Shortened URL already previously created
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                    description: The shortened URL
        '201':
          description: Shortened URL created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                    description: The shortened URL
  /{short-url}:
    get:
      summary: Redirect to original URL
      parameters:
        - name: short-url
          in: path
          required: true
          schema:
            type: string
          description: The shortened URL
      responses:
        '302':
          description: Redirects to the original URL
        '404':
          description: Shortened URL not found
          content:
            text/plain:
              schema:
                type: string

components:
  schemas: